name: wallet_guard
description: "Track and manage your transaction"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.0

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true